# Introduction toTensorflow

![Tensorflow](images/TFlogo.png)

## What is Tensorflow?

- Originally developed by the **Google** Brain Team within Google's Machine Intelligence research organization 
- TensorFlow is a **suite of software**, an ecosystem for developing deep learning models.
- An open source software library for numerical computation using **data flow graphs**.
- TensorFlow provides primitives for defining functions on **tensors** and automatically computing their derivatives. 

## Why Tensorflow

- Faster compile times, based on C/C++.
- Python and C++ API.
- Support CPUs, GPUs, and distributed processing.
- Different components that help to expose functionality and to visualize internal complex processes.

## Tensorflow Components

#### TensorFlow(API)

This component of tensorflow contains the API's to define the models and train the models with the data.The actual computation was written in C++ though it is accessed with python API's.This advantages are of 2 fold:
- We get the more user friendly python interface to develop the models 
- We can run the models on fast and efficient compiled C++ code.

#### TensorFlow Serving

This component of tensorflow helps to deploy the pretrained models.Tensorflow serving is capable of switching from old models to new models with out any downtime.This is the stand out feature in the ecosystem.This is also written in C++ and can be accessible with python interfaces.

#### TensorBoard:

The third component of the ecosystem and the boon for engineers is the TensorBoard. It helps to analyze, visualize, and debug TensorFlow graphs.


## Data Flow Graph? 
![Tensorflow Graph](images/TensorflowGraph.png)
- Computations are represented as graphs.
    - Nodes are the operations (ops).
    - Edges are the Tensors (multidimensional arrays).
- Typical program consists of 2 phases: 
    - Construction phase: assembling a graph (model).
    - Execution phase: pushing data through the graph.

## Tensor? 
Tensors can be viewed as a multidimensional array of numbers. This means that: 
- A scalar is a tensor, 
- A vector is a tensor, and 
- A matrix is a tensor.
![Tensor](images/Tensor.png)

## Understanding Tensorflow Graph and Operations

#### Import Tensorflow module

In [1]:
import tensorflow as tf

#### TensorFlow Session Object
> A Session object encapsulates the environment in which
Tensor objects are evaluated.

> All computations add nodes to global default graph.

[Tensorflow Docs](https://www.tensorflow.org/versions/r0.8/api_docs/python/client.html#Session)

In [3]:
# Constructing computational graph
a = tf.constant(5)
b = tf.constant(6)
c= a * b

In [4]:
# Run default graph session
with tf.Session() as sess:
    print(c)
    print(sess.run(c))
    print(c.eval())
    print(c)

Tensor("mul:0", shape=(), dtype=int32)
30
30
Tensor("mul:0", shape=(), dtype=int32)


`c.eval()` is just syntactic sugar for `sess.run(c)` in the currently active session!

#### TensorFlow Variables
> When you train a model you use variables to hold and
update parameters. Variables are in-memory buffers
containing tensors.

All tensors we’ve used previously have been constant tensors, not variables.

##### TensorFlow variables must be initialized before they have values! Contrast with constant tensors.

In [6]:
W1 = tf.ones((2,2))
W2 = tf.Variable(tf.zeros((2,2)), name="weights")
with tf.Session() as sess:
    print(sess.run(W1))
    sess.run(tf.global_variables_initializer())
    print(sess.run(W2))


[[ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.]
 [ 0.  0.]]


##### Variable objects can be initialized from constants or random values

In [8]:
# initialize from constant values
W = tf.Variable(tf.zeros((2,2)), name="weights")
# initialize from random values
R = tf.Variable(tf.random_normal((2,2)), name="random_weights")

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(W))
    print(sess.run(R))


[[ 0.  0.]
 [ 0.  0.]]
[[-0.48949656 -0.21983659]
 [ 0.94058114  1.52746809]]


##### Updating Variable State

In [10]:

#initialize state variable
state = tf.Variable(0, name="counter")
#initialize new_value as: new_value = state + 1
new_value = tf.add(state, tf.constant(1))
# initialize state as: state = new_value
update = tf.assign(state, new_value)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


##### Fetching Variable State

In [16]:
# initializing constants
input1 = tf.constant(3.0)
input2 = tf.constant(2.0)
input3 = tf.constant(5.0)

#intermiate operation
intermed = tf.add(input2, input3)

# final operation
mul = tf.multiply(input1, intermed)

# Calling sess.run(var) on a tf.Session() object retrieves its value. 
# Can retrieve multiple variables simultaneously with sess.run([var1, var2])
with tf.Session() as sess:
    result = sess.run([mul, intermed])
    print(result)


[21.0, 7.0]


##### Placeholders and Feed Dictionaries
- Use tf.placeholder variables (dummy nodes that provide entry points for data to computational graph).
- A feed_dict is a python dictionary mapping from tf. placeholder vars (or their names) to data (numpy arrays,lists, etc.).

In [18]:
# Define tf.placeholder objects for data entry.
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)

output = tf.multiply(input1, input2)

with tf.Session() as sess:
    # Feed data into computation graph
    print(sess.run([output], feed_dict={input1:[7.], input2:[2.]}))


[array([ 14.], dtype=float32)]
